import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

plugins {
    id 'jacoco'
    id 'java'
    id 'org.springframework.boot' version '3.5.12'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.openapi.generator' version '7.9.0'
    id "org.sonarqube" version "4.4.1.3373"
}

def packageName = 'com.challenge.accounts_movements_service'

group = 'com.challenge'
version = '0.0.1-SNAPSHOT'

group = "${packageName}"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named("sonarqube") {
    dependsOn tasks.named("jacocoTestReport")
}

sonar {
    properties {
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"
    }
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
    gradlePluginPortal()
    mavenCentral()
    maven { url "https://plugins.gradle.org/m2/" }
    mavenLocal()
}

ext {
    lombokVersion = '1.18.34'
}

dependencies {
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.8.16'
    implementation 'org.springframework.session:spring-session-jdbc'
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'com.intuit.karate:karate-junit5:1.4.1'
    testImplementation 'org.testcontainers:junit-jupiter:1.20.4'
    testImplementation 'org.testcontainers:postgresql:1.20.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'com.h2database:h2'
}

tasks.register('buildSpringServer', GenerateTask) {
    generatorName = "spring"
    templateDir = "$rootDir/src/main/resources/openapi-templates"
    inputSpec = "$rootDir/src/main/resources/openapi.yaml".toString()
    outputDir = "$buildDir/generated".toString()
    apiPackage = "${packageName}.infrastructure.input.adapter.rest.customer_service"
    modelPackage = "${packageName}.infrastructure.input.adapter.rest.customer_service.bean"
    library = "spring-boot"
    configOptions = [skipDefaultInterface                    : "true",
                     useSpringBoot3                          : "true",
                     useJakartaEe                            : "true",
                     serializableModel                       : "true",
                     dateLibrary                             : "java8",
                     openApiNullable                         : "false",
                     reactive                                : "true",
                     apiFirst                                : "false",
                     delegatePattern                         : "false",
                     configPackage                           : "${packageName}.infrastructure.input.adapter.rest.customer_service.config",
                     sourceFolder                            : "src/main/java",
                     basePackage                             : "com.challenge",
                     disallowAdditionalPropertiesIfNotPresent: "true",
                     interfaceOnly                           : "true"]
}

tasks.register('buildSpringClientCustomerService', GenerateTask) {
    generatorName = "java"
    inputSpec = "$rootDir/src/main/resources/customer_service.yaml".toString()
    templateDir = "$rootDir/src/main/resources/openapi-templates/client"
    apiPackage = "${packageName}.infrastructure.output.adapter.rest.customer_service"
    modelPackage = "${packageName}.infrastructure.output.adapter.rest.customer_service.bean"
    outputDir = "$buildDir/generated".toString()
    library = "webclient"
    configOptions = [useSpringBoot3 : "true",
                     useJakartaEe   : "true",
                     openApiNullable: "false",
                     sourceFolder   : "src/main/java",
                     configPackage  : "${packageName}.infrastructure.output.adapter.rest.customer_service.config"]
}

compileJava {
    dependsOn buildSpringServer, buildSpringClientCustomerService
    options.compilerArgs += [
            "-Amapstruct.suppressGeneratorTimestamp=true",
            "-Amapstruct.suppressGeneratorVersionInfoComment=true",
            "-Amapstruct.verbose=true",
            "-Amapstruct.defaultComponentModel=spring"
    ]
}

sourceSets.main.java.srcDirs = ["$buildDir/generated/src/main/java", "src/main/java"]

springBoot{
    buildInfo()
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        xml.destination file("$buildDir/jacoco/test.xml")
        html.destination file("$buildDir/jacoco/index.html")
        xml.destination file("$buildDir/reports/jacoco/test/jacocoTestReport.xml")
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/test/html"))
        html.required = true
        csv.required = true
    }
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.00
            }
        }
    }
}

test.finalizedBy jacocoTestReport, jacocoTestCoverageVerification

check.dependsOn jacocoTestCoverageVerification
